//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IVoidService")]
public interface IVoidService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidService/CreateUser", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidService/CreateUserResponse")]
    bool CreateUser(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidService/CreateUser", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidService/CreateUserResponse")]
    System.Threading.Tasks.Task<bool> CreateUserAsync(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidService/Login", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidService/LoginResponse")]
    bool Login(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidService/Login", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidService/LoginResponse")]
    System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidService/ChangePassword", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidService/ChangePasswordResponse")]
    bool ChangePassword(string username, string password, string newPassword);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IVoidService/ChangePassword", ReplyAction="http://Microsoft.ServiceModel.Samples/IVoidService/ChangePasswordResponse")]
    System.Threading.Tasks.Task<bool> ChangePasswordAsync(string username, string password, string newPassword);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IVoidServiceChannel : IVoidService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VoidServiceClient : System.ServiceModel.ClientBase<IVoidService>, IVoidService
{
    
    public VoidServiceClient()
    {
    }
    
    public VoidServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VoidServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VoidServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VoidServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool CreateUser(string username, string password)
    {
        return base.Channel.CreateUser(username, password);
    }
    
    public System.Threading.Tasks.Task<bool> CreateUserAsync(string username, string password)
    {
        return base.Channel.CreateUserAsync(username, password);
    }
    
    public bool Login(string username, string password)
    {
        return base.Channel.Login(username, password);
    }
    
    public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password)
    {
        return base.Channel.LoginAsync(username, password);
    }
    
    public bool ChangePassword(string username, string password, string newPassword)
    {
        return base.Channel.ChangePassword(username, password, newPassword);
    }
    
    public System.Threading.Tasks.Task<bool> ChangePasswordAsync(string username, string password, string newPassword)
    {
        return base.Channel.ChangePasswordAsync(username, password, newPassword);
    }
}
